apps/cart/urls.py
from django.conf.urls import url

urlpatterns = [

]

apps/goods/urls.py
from django.conf.urls import url, include

from apps.goods import views

urlpatterns = [
    url('^index$', views.IndexView.as_view(), name='index'),
    # 127.0.0.1:8000/detail/商品Id
    url('^detail/(\d+)$', views.DetailView.as_view(), name='detail'),

    url('^list/(\d+)/(\d+)$', views.ListView.as_view(), name='list'),
]

apps/users/urls.py
from django.conf.urls import url

from apps.users import views

urlpatterns = [

    # url(r'^register$', views.register,name='register'),     # 进入注册界面
    # url(r'^do_register$', views.do_register, name="do_register"),     # 进入注册界面
    url(r'^register$', views.RegisterView.as_view(), name="register"),     # 进入注册界面 返回一个视图函数
    url(r'^login$', views.LoginView.as_view(), name='login'),         # 登录
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),         # 登出

    url(r'^active/(.+)$', views.ActiveView.as_view(), name="active"), # 激活视图

    url(r'^address$', views.UserAddressViem.as_view(), name='address'),  # 地址页面
    url(r'^orders$', views.UserOrderViem.as_view(), name='orders'),  # 订单页面
    url(r'^$', views.UserInfoView.as_view(), name='info'),  # 个人用户界面
]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r"^users/", include('apps.users.urls', namespace='users')),
    url(r"^cart/", include('apps.cart.urls', namespace='cart')),
    url(r"^orders/", include('apps.orders.urls', namespace='orders')),

    url(r'^tinymce/', include('tinymce.urls')),

    url(r"^", include('apps.goods.urls', namespace='goods')),
    # 商品模块 /index

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load staticfiles %}

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}
	{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	{# 顶部的js #}
    {% block top_js %}
        <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}

</head>
<body>

    {# 顶部信息栏 #}
    {% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {# 显示登录的用户名 #}
                {% if user.is_authenticated %}
                    {# 已经登录 #}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'users:logout' %}">注销</a>
                    </div>
                {% else %}
                    {# 未登录 #}
                    <div class="login_btn fl">
                        <a href="{% url 'users:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'users:register' %}">注册</a>
                    </div>
                {% endif %}


				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'users:orders' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% endblock %}

    {# 搜索栏 #}
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
    {% endblock %}

	{# 主体内容 #}
    {% block body %}
    {% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

	{# 底部的js #}
    {% block bottom_js %}
    {% endblock %}

</body>
</html>

templates/base_no_cart.html
{# 搜索栏没有购物车: 购物车界面, 下单界面, 用户中心 #}
{% extends 'base.html' %}

{% load staticfiles %}

{# 重写父类搜索栏: 去掉购物车栏 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock %}</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>
{% endblock %}

templates/base_user_center.html
{#用户中心三个界面的父模板#}
{% extends 'base_no_cart.html' %}
{% block title %}
{% endblock %}

{% block page_title %}
    用户中心
{% endblock %}
{% block body %}
    <div class="main_con clearfix">
{#    左侧部分#}
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{%  url 'users:info' %}" {% if which_page == 1 %}class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{%  url 'users:orders' %}" {% if which_page == 2 %}class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{%  url 'users:address' %}" {% if which_page == 3 %}class="active"{% endif %} >· 收货地址</a></li>
            </ul>
        </div>
{#    右测部分#}
    {% block right_body %}
    {% endblock %}
    </div>
{% endblock %}

templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods012.jpg"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods003.jpg"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block title %}
天天生鲜—商品详情
{% endblock %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for category in categories %}
                        <li><a href="{% url 'goods:list' category.id 1 %}?sort=default"
                               class="{{ category.log }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.category.id 1 %}?sort=default">{{ sku.category.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.title }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unit }}</span>
			</div>
            {# 其他商品显示#}
            {% if other_skus %}
                <div>
                    <p>其他规格:</p>
                    <ul>
                        {% for sku in other_skus %}
                            <li><a href="{% url 'goods:detail' sku.id %}" >{{ sku.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {%  endif %}

			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
{#                    显示当前类别下的新品#}
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{sku.default_image.url}}"></a>
                            <h4><a href="{%  url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{sku.price}}</div>
                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.spu.desc|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>

{% endblock %}
{% block bottom_js %}
	<div class="add_jump"></div>

	<script type="text/javascript" src="js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    天天生鲜 首页
{% endblock %}
{% block top_js %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">

        <ul class="subnav fl">
            {% for category in categories %}
                 <li><a href="#model0{{ forloop.counter }}"
                        class="{{ category.logo }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                {#   显示轮播图#}
                {% for slide_sku in slide_skus %}
                    {# 轮播图连接Sku再找到Id,#}
                    <a href="{% url 'goods:detail' slide_sku.sku.id %}">
                        <li><img src="{{ slide_sku.image.url }}" alt="幻灯片"></li>
                    </a>

                {% endfor %}
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            {#显示促销活动#}
            {% for promotion in promotions %}
                <a href="#"><img src="{{ promotion.image.url }}"></a>
            {% endfor %}
        </div>
    </div>

    {% for category in categories %}
        <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model01">{{ category.name }}</h3>
            <div class="subtitle fl">
                <span>|</span>
                {#显示文字类别#}
                {% for c_sku in category.text_skus %}
                    <a href="{% url 'goods:detail' c_sku.sku.id %}">{{ c_sku.sku.name }}</a>
                {% endfor %}
            </div>
            <a href="{% url 'goods:list' category.id 1 %}?sort=default"
               class="goods_more fr" id="fruit_more">查看更多 ></a>
        </div>

        <div class="goods_con clearfix">
            <div class="goods_banner fl"><img src="{{ category.image.url }}"></div>
            <ul class="goods_list fl">
                {#显示图片商品#}
                {% for c_sku in category.image_skus %}
                     <li>
                        <h4><a href="{% url 'goods:detail' c_sku.sku.id %}">{{ c_sku.sku.name }}</a></h4>
                        <a href="{% url 'goods:detail' c_sku.sku.id %}"><img src="{{ c_sku.sku.default_image.url }}"></a>
                        <div class="prize">¥ {{ c_sku.sku.price }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endfor %}
{% endblock %}
{% block bottom_js %}
    <script type="text/javascript" src="js/slideshow.js"></script>
    <script type="text/javascript">
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        }
    </script>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block title %}
天天生鲜-商品列表
{% endblock %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{# 显示所有的类别 #}
                    {% for category in categories %}
                        {# 默认跳转到某个分类商品列表的第一页 #}
                        <li><a href="{% url 'goods:list' category.id 1 %}?sort=default"
                               class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' category.id 1 %}?sort=default">{{ category.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{#  显示当前类别下的新品#}
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{sku.default_image.url}}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{sku.price}}</div>
                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				{# 显示排序条件: 并设置当前选中的是哪一项 #}
                <a href="{% url 'goods:list' category.id 1 %}?sort=default"
                   {% if sort == 'default' %}class="active"{% endif %}>默认</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=price"
                   {% if sort == 'price' %}class="active"{% endif %}>价格</a>
                <a href="{% url 'goods:list' category.id 1 %}?sort=hot"
                   {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {#显示当前类别下的商品#}
                {% for sku in page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %} ">
                        <img src="{{ sku.default_image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

            <div class="pagenation">
                {% if page.has_previous %}
                    <a href="{% url 'goods:list' category.id page.previous_page_number %}?sort={{ sort }}">
                        &lt;上一页</a>
                {% endif %}

                {% for index in page_range %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}"
                       {% if index == page.number %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}
                {% if page.has_next %}
                    <a href="{% url 'goods:list' category.id page.next_page_number %}?sort={{ sort }}">
                        下一页&gt;</a>
                {% endif %}
            </div>
		</div>
	</div>

{% endblock %}

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">


{% load staticfiles %}
<head>

	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
{#	<link rel="stylesheet" type="text/css" href="css/reset.css">#}
{#	<link rel="stylesheet" type="text/css" href="css/main.css">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<a href={% url 'goods:index' %}"index.html" class="login_logo"><img src={% static "images/logo02.png" %}></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
                            <!-- 登录出错信息提示 -->
                            <div style="color: red">{{ errmsg }}</div>
							<input type="checkbox" name="remember">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_body %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user.username }}0</li>
                <li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
                <li><span>联系地址：</span>{{ address.detail_addr }}</li>
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for sku in skus %}
                      <li>
                        <a href="detail.html"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="detail.html">{{ sku.id }}{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>

                {% endfor %}


            </ul>
        </div>
    </div>
{% endblock %}

templates/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_body %}
    <div class="right_content clearfix">
        <h3 class="common_title2">收货地址</h3>
        <div class="site_con">
            {% if address %}
                <dl>
                    <dt>当前地址：</dt>
                    <dd>{{ address.detail_addr }}（{{ address.receiver_name }} 收）
                        {{ address.receiver_mobile }} </dd>
                </dl>
            {% else %}
                <dl>
                    <dt>当前没有地址！</dt>
                </dl>
            {% endif %}

        </div>
        <h3 class="common_title2">编辑地址</h3>
        <div class="site_con">

            <form method="post" action="{% url 'users:address' %}">
                {% csrf_token %}
                <div class="form_group">
                    <label>收件人：</label>
                    <input type="text" name="receiver">
                </div>
                <div class="form_group form_group2">
                    <label>详细地址：</label>
                    <textarea class="site_area" name="detail"></textarea>
                </div>
                <div class="form_group">
                    <label>邮编：</label>
                    <input type="text" name="zip_code">
                </div>
                <div class="form_group">
                    <label>手机：</label>
                    <input type="text" name="mobile">
                </div>

                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>
{% endblock %}